### ISSUE TITLE
TypeError exception with desired properties message

### ISSUE THREAD

**Issue by packnologyusa** [iotblackbelt/node-red-contrib-azure-iot-device#24]
Hi,

I just added a desired (writable) property to my device template in IOT Central and then updated the property value on the device twin. Now my node-red crashes on start-up with the following log entries. I hope you can help.

Regards,
Greg

23 Aug 11:02:32 - [info] [azureiotdevice:ae934fbf.de102] 2bbh5tif9v2 -> Desired properties received: {"sizerHost":"host.docker.internal","$version":2}
23 Aug 11:02:32 - [red] Uncaught Exception:
23 Aug 11:02:32 - TypeError: Cannot read property 'toString' of undefined
    at MqttTwinClient._sendTwinRequest (/data/node_modules/azure-iot-device-mqtt/dist/mqtt_twin_client.js:201:40)
    at /data/node_modules/azure-iot-device-mqtt/dist/mqtt_twin_client.js:157:23
    at BehavioralFsm.subscribe (/data/node_modules/azure-iot-device-mqtt/dist/mqtt_twin_client.js:92:25)
    at BehavioralFsm.handle (/data/node_modules/machina/lib/machina.js:613:25)
    at BehavioralFsm.subscribe (/data/node_modules/azure-iot-device-mqtt/dist/mqtt_twin_client.js:115:22)
    at MqttTwinClient.updateTwinReportedProperties (/data/node_modules/azure-iot-device-mqtt/dist/mqtt_twin_client.js:149:24)
    at constructor.updateTwinReportedProperties (/data/node_modules/azure-iot-device-mqtt/dist/mqtt.js:383:105)
    at constructor.handle (/data/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (/data/node_modules/machina/lib/machina.js:466:63)
    at Mqtt.updateTwinReportedProperties (/data/node_modules/azure-iot-device-mqtt/dist/mqtt.js:671:19)
    at /data/node_modules/azure-iot-device/dist/twin.js:115:30
    at retryOperation (/data/node_modules/azure-iot-common/dist/retry_operation.js:36:13)
    at RetryOperation.retry (/data/node_modules/azure-iot-common/dist/retry_operation.js:67:9)
    at Twin._updateReportedProperties (/data/node_modules/azure-iot-device/dist/twin.js:113:17)
    at Object.update (/data/node_modules/azure-iot-device/dist/twin.js:145:26)
    at sendDeviceProperties (/data/node_modules/node-red-contrib-azure-iot-device/azureiotdevice/azureiotdevice.js:504:38)

**Comment by iotblackbelt** [comment]
@packnology do you have more details on the scenario, so I can replay? What is it that you setup in IoTC? Thanks!

**Comment by iotblackbelt** [comment]
Will be fixed in 0.2.4 version.
